baseURL = "https://your-crypto-news.netlify.app/"
title = "My New Hugo Site"
theme = "ananke"
languageCode = "zh-tw"
languageName = "繁體中文"

[params]
  version = "0.2.X"
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "標籤"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "分類"
    url = "/categories/"
    weight = 3

[markup]
  [markup.highlight]
    noClasses = false

